"""
Email report sender - sends daily prospect reports
Uses GitHub Actions built-in email capability
"""

import logging
import os
from typing import List, Dict
from datetime import datetime

logger = logging.getLogger(__name__)


class EmailReporter:
    """Sends HTML email reports with prospects"""

    def __init__(self):
        """Initialize email reporter"""
        logger.info("Email reporter initialized")

    def generate_html_report(self, prospects: List[Dict]) -> str:
        """Generate beautiful HTML email report"""

        # Sort by score
        high_priority = [p for p in prospects if p.get('priority') == 'HIGH']
        medium_priority = [p for p in prospects if p.get('priority') == 'MEDIUM']

        html = f"""
<!DOCTYPE html>
<html>
<head>
    <style>
        body {{ font-family: Arial, sans-serif; margin: 20px; background-color: #f5f5f5; }}
        .header {{ background-color: #2563eb; color: white; padding: 20px; border-radius: 8px; }}
        .summary {{ background-color: white; padding: 20px; margin: 20px 0; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }}
        .prospect {{ background-color: white; padding: 20px; margin: 10px 0; border-radius: 8px; border-left: 4px solid #2563eb; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }}
        .prospect.high {{ border-left-color: #dc2626; }}
        .prospect.medium {{ border-left-color: #f59e0b; }}
        .prospect-name {{ font-size: 18px; font-weight: bold; color: #1f2937; margin-bottom: 8px; }}
        .prospect-company {{ color: #6b7280; margin-bottom: 12px; }}
        .prospect-bio {{ color: #374151; margin-bottom: 12px; line-height: 1.6; }}
        .score-badge {{ display: inline-block; padding: 4px 12px; border-radius: 12px; font-weight: bold; font-size: 14px; }}
        .score-high {{ background-color: #fee2e2; color: #dc2626; }}
        .score-medium {{ background-color: #fef3c7; color: #f59e0b; }}
        .links {{ margin-top: 12px; }}
        .links a {{ color: #2563eb; text-decoration: none; margin-right: 16px; }}
        .links a:hover {{ text-decoration: underline; }}
        .reasoning {{ background-color: #f9fafb; padding: 12px; border-radius: 6px; margin-top: 12px; font-size: 14px; color: #4b5563; }}
        .footer {{ text-align: center; color: #6b7280; margin-top: 40px; padding: 20px; }}
    </style>
</head>
<body>
    <div class="header">
        <h1>🚀 Daily Founder Report - {datetime.now().strftime('%B %d, %Y')}</h1>
        <p>Illinois founders matching Superior Studios investment thesis</p>
    </div>

    <div class="summary">
        <h2>📊 Summary</h2>
        <p><strong>Total Prospects:</strong> {len(prospects)}</p>
        <p><strong>High Priority:</strong> {len(high_priority)} founders</p>
        <p><strong>Medium Priority:</strong> {len(medium_priority)} founders</p>
    </div>
"""

        # High priority prospects
        if high_priority:
            html += """
    <div class="summary">
        <h2>⭐ High Priority Founders (Reach Out Today)</h2>
"""
            for prospect in high_priority[:10]:  # Top 10
                html += self._format_prospect(prospect, 'high')
            html += "</div>"

        # Medium priority prospects
        if medium_priority:
            html += """
    <div class="summary">
        <h2>📋 Medium Priority Founders</h2>
"""
            for prospect in medium_priority[:10]:  # Top 10
                html += self._format_prospect(prospect, 'medium')
            html += "</div>"

        html += """
    <div class="footer">
        <p>Generated by Superior Studios Sourcing Engine</p>
        <p>Powered by Claude AI</p>
    </div>
</body>
</html>
"""
        return html

    def _format_prospect(self, prospect: Dict, priority: str) -> str:
        """Format a single prospect as HTML"""
        name = prospect.get('name', 'Unknown')
        email = prospect.get('email', '')
        company = prospect.get('company', '')
        location = prospect.get('location', '')
        bio = prospect.get('bio', '')
        score = prospect.get('overall_score', 0)
        reasoning = prospect.get('reasoning', '')
        linkedin = prospect.get('linkedin_url', '')
        twitter = prospect.get('twitter_url', '')
        github = prospect.get('github_url', '')
        website = prospect.get('website', '')

        score_class = 'score-high' if priority == 'high' else 'score-medium'

        links = []
        if linkedin:
            links.append(f'<a href="{linkedin}" target="_blank">LinkedIn</a>')
        if twitter:
            links.append(f'<a href="{twitter}" target="_blank">Twitter</a>')
        if github:
            links.append(f'<a href="{github}" target="_blank">GitHub</a>')
        if website:
            links.append(f'<a href="{website}" target="_blank">Website</a>')
        if email:
            links.append(f'<a href="mailto:{email}">Email</a>')

        links_html = ' | '.join(links) if links else ''

        return f"""
        <div class="prospect {priority}">
            <div class="prospect-name">{name} <span class="{score_class} score-badge">{score}/100</span></div>
            <div class="prospect-company">{company} • {location}</div>
            <div class="prospect-bio">{bio[:300]}{'...' if len(bio) > 300 else ''}</div>
            <div class="links">{links_html}</div>
            <div class="reasoning"><strong>Why this founder:</strong> {reasoning[:200]}{'...' if len(reasoning) > 200 else ''}</div>
        </div>
"""

    def save_report(self, prospects: List[Dict], filepath: str = 'daily_report.html'):
        """Save HTML report to file"""
        try:
            html = self.generate_html_report(prospects)

            with open(filepath, 'w', encoding='utf-8') as f:
                f.write(html)

            logger.info(f"✅ Saved HTML report: {filepath}")
            return filepath

        except Exception as e:
            logger.error(f"Error saving report: {str(e)}")
            return None
